export const Applications = [
    {
        applicationId: 1,
        candidateId: 4,
        checkerId: 2,
        professionalTitle: "Social Worker",
        hometownAddress: "Quang Binh",
        expectedSalary: "2,164,505",
        currency: "₩",
        preferredWork: "Farmer",
        academicBackground: "Upper secondary",
        expectedArea: "Sejong City",
        familySituation: "Medium",
        marriedStatus: "Married",
        numberOfFamily: "2",
        passportImg:
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReuEECQzwR2I_bFMxpB-03M4Bgoz5ivATToqiorqdvow&s",
        healthCheckImg:
            "https://novalaw.vn/wp-content/uploads/2022/10/Sample-of-a-work-permit-health-check-certificate-issued-in-Vietnam.png",
        policeCheckImg:
            "https://www.vietnamimmigration.com/wp-content/uploads/2021/07/criminal-record-certificate-no.2.jpg",
        koreanExamImg: "https://media.cakeresume.com/image/upload/v1628180772/murftgok0yzzhhkwn3r0.png",
        idCardFrontImg: "https://lawnet.vn/uploads/image/2023/06/03/014312635.jpg",
        idCardBackImg: "https://cdnimgen.vietnamplus.vn/t620/uploaded/wbxx/2021_02_24/chip_based_id_card_back.jpg",
        status: "Waiting",
        note: "",
        dateApplying: "March 25, 2023"
    },
    {
        applicationId: 2,
        candidateId: 4,
        checkerId: 3,
        professionalTitle: "Medic",
        hometownAddress: "Moc Bai",
        expectedSalary: "2,069,169",
        currency: "₩",
        preferredWork: "Farmer",
        academicBackground: "Lower secondary",
        expectedArea: "Changwon",
        familySituation: "Medium",
        marriedStatus: "Married",
        numberOfFamily: "3",
        passportImg:
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReuEECQzwR2I_bFMxpB-03M4Bgoz5ivATToqiorqdvow&s",
        healthCheckImg:
            "https://novalaw.vn/wp-content/uploads/2022/10/Sample-of-a-work-permit-health-check-certificate-issued-in-Vietnam.png",
        policeCheckImg:
            "https://www.vietnamimmigration.com/wp-content/uploads/2021/07/criminal-record-certificate-no.2.jpg",
        koreanExamImg: "https://media.cakeresume.com/image/upload/v1628180772/murftgok0yzzhhkwn3r0.png",
        idCardFrontImg: "https://lawnet.vn/uploads/image/2023/06/03/014312635.jpg",
        idCardBackImg: "https://cdnimgen.vietnamplus.vn/t620/uploaded/wbxx/2021_02_24/chip_based_id_card_back.jpg",
        status: "Waiting",
        note: "",
        dateApplying: "January 16, 2023"
    },
    {
        applicationId: 3,
        candidateId: 5,
        checkerId: 2,
        professionalTitle: "Salesman",
        hometownAddress: "Ho Chi Minh",
        expectedSalary: "2,292,860",
        currency: "₩",
        preferredWork: "Waiter/Waitress",
        academicBackground: "Bachelor",
        expectedArea: "Anyang",
        familySituation: "Low",
        numberOfFamily: "1",
        passportImg:
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReuEECQzwR2I_bFMxpB-03M4Bgoz5ivATToqiorqdvow&s",
        healthCheckImg:
            "https://novalaw.vn/wp-content/uploads/2022/10/Sample-of-a-work-permit-health-check-certificate-issued-in-Vietnam.png",
        policeCheckImg:
            "https://www.vietnamimmigration.com/wp-content/uploads/2021/07/criminal-record-certificate-no.2.jpg",
        koreanExamImg: "https://media.cakeresume.com/image/upload/v1628180772/murftgok0yzzhhkwn3r0.png",
        idCardFrontImg: "https://lawnet.vn/uploads/image/2023/06/03/014312635.jpg",
        idCardBackImg: "https://cdnimgen.vietnamplus.vn/t620/uploaded/wbxx/2021_02_24/chip_based_id_card_back.jpg",
        status: "Waiting",
        note: "",
        dateApplying: "January 12, 2023"
    },
    {
        applicationId: 4,
        candidateId: 6,
        checkerId: 3,
        professionalTitle: "Lawer",
        hometownAddress: "Quang Tri",
        expectedSalary: "2,369,491",
        currency: "₩",
        preferredWork: "Construction Worker",
        academicBackground: "Upper secondary",
        expectedArea: "Gimpo",
        familySituation: "Medium",
        marriedStatus: "Married",
        numberOfFamily: "5",
        passportImg:
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReuEECQzwR2I_bFMxpB-03M4Bgoz5ivATToqiorqdvow&s",
        healthCheckImg:
            "https://novalaw.vn/wp-content/uploads/2022/10/Sample-of-a-work-permit-health-check-certificate-issued-in-Vietnam.png",
        policeCheckImg:
            "https://www.vietnamimmigration.com/wp-content/uploads/2021/07/criminal-record-certificate-no.2.jpg",
        koreanExamImg: "https://media.cakeresume.com/image/upload/v1628180772/murftgok0yzzhhkwn3r0.png",
        idCardFrontImg: "https://lawnet.vn/uploads/image/2023/06/03/014312635.jpg",
        idCardBackImg: "https://cdnimgen.vietnamplus.vn/t620/uploaded/wbxx/2021_02_24/chip_based_id_card_back.jpg",
        status: "Waiting",
        note: "",
        dateApplying: "May 12, 2023"
    },
    {
        applicationId: 5,
        candidateId: 7,
        checkerId: 3,
        professionalTitle: "Journalist",
        hometownAddress: "Quang Binh",
        expectedSalary: "2,053,093",
        currency: "₩",
        preferredWork: "Farmer",
        academicBackground: "Primary",
        expectedArea: "Ansan",
        familySituation: "Low",
        marriedStatus: "Single",
        numberOfFamily: "3",
        passportImg:
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReuEECQzwR2I_bFMxpB-03M4Bgoz5ivATToqiorqdvow&s",
        healthCheckImg:
            "https://novalaw.vn/wp-content/uploads/2022/10/Sample-of-a-work-permit-health-check-certificate-issued-in-Vietnam.png",
        policeCheckImg:
            "https://www.vietnamimmigration.com/wp-content/uploads/2021/07/criminal-record-certificate-no.2.jpg",
        koreanExamImg: "https://media.cakeresume.com/image/upload/v1628180772/murftgok0yzzhhkwn3r0.png",
        idCardFrontImg: "https://lawnet.vn/uploads/image/2023/06/03/014312635.jpg",
        idCardBackImg: "https://cdnimgen.vietnamplus.vn/t620/uploaded/wbxx/2021_02_24/chip_based_id_card_back.jpg",
        status: "Waiting",
        note: "",
        dateApplying: "March 23, 2023"
    },
    {
        applicationId: 6,
        candidateId: 8,
        checkerId: 2,
        professionalTitle: "Social Worker",
        hometownAddress: "Hai Duong",
        expectedSalary: "2,125,615",
        currency: "₩",
        preferredWork: "Fruit Picker",
        academicBackground: "Lower secondary",
        expectedArea: "Jinju",
        familySituation: "High",
        marriedStatus: "Married",
        numberOfFamily: "2",
        passportImg:
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReuEECQzwR2I_bFMxpB-03M4Bgoz5ivATToqiorqdvow&s",
        healthCheckImg:
            "https://novalaw.vn/wp-content/uploads/2022/10/Sample-of-a-work-permit-health-check-certificate-issued-in-Vietnam.png",
        policeCheckImg:
            "https://www.vietnamimmigration.com/wp-content/uploads/2021/07/criminal-record-certificate-no.2.jpg",
        koreanExamImg: "https://media.cakeresume.com/image/upload/v1628180772/murftgok0yzzhhkwn3r0.png",
        idCardFrontImg: "https://lawnet.vn/uploads/image/2023/06/03/014312635.jpg",
        idCardBackImg: "https://cdnimgen.vietnamplus.vn/t620/uploaded/wbxx/2021_02_24/chip_based_id_card_back.jpg",
        status: "Waiting",
        note: "",
        dateApplying: "August 28, 2023"
    },
    {
        applicationId: 7,
        candidateId: 9,
        checkerId: 2,
        professionalTitle: "Manager",
        hometownAddress: "Hai Phong",
        expectedSalary: "2,010,017",
        currency: "₩",
        preferredWork: "Lawner",
        academicBackground: "Bachelor",
        expectedArea: "Cheongju",
        familySituation: "Medium",
        marriedStatus: "Married",
        numberOfFamily: "Single",
        passportImg:
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReuEECQzwR2I_bFMxpB-03M4Bgoz5ivATToqiorqdvow&s",
        healthCheckImg:
            "https://novalaw.vn/wp-content/uploads/2022/10/Sample-of-a-work-permit-health-check-certificate-issued-in-Vietnam.png",
        policeCheckImg:
            "https://www.vietnamimmigration.com/wp-content/uploads/2021/07/criminal-record-certificate-no.2.jpg",
        koreanExamImg: "https://media.cakeresume.com/image/upload/v1628180772/murftgok0yzzhhkwn3r0.png",
        idCardFrontImg: "https://lawnet.vn/uploads/image/2023/06/03/014312635.jpg",
        idCardBackImg: "https://cdnimgen.vietnamplus.vn/t620/uploaded/wbxx/2021_02_24/chip_based_id_card_back.jpg",
        status: "Waiting",
        note: "",
        dateApplying: "June 22, 2023"
    },
    {
        applicationId: 8,
        candidateId: 10,
        checkerId: 3,
        professionalTitle: "Social Worker",
        hometownAddress: "Ha Noi",
        expectedSalary: "2,217,312",
        currency: "₩",
        preferredWork: "Waiter/Waitress",
        academicBackground: "Primary",
        expectedArea: "Gyeongju",
        familySituation: "Low",
        marriedStatus: "Married",
        numberOfFamily: "0",
        passportImg:
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReuEECQzwR2I_bFMxpB-03M4Bgoz5ivATToqiorqdvow&s",
        healthCheckImg:
            "https://novalaw.vn/wp-content/uploads/2022/10/Sample-of-a-work-permit-health-check-certificate-issued-in-Vietnam.png",
        policeCheckImg:
            "https://www.vietnamimmigration.com/wp-content/uploads/2021/07/criminal-record-certificate-no.2.jpg",
        koreanExamImg: "https://media.cakeresume.com/image/upload/v1628180772/murftgok0yzzhhkwn3r0.png",
        idCardFrontImg: "https://lawnet.vn/uploads/image/2023/06/03/014312635.jpg",
        idCardBackImg: "https://cdnimgen.vietnamplus.vn/t620/uploaded/wbxx/2021_02_24/chip_based_id_card_back.jpg",
        status: "Waiting",
        note: "",
        dateApplying: "February 12, 2023"
    },
    {
        applicationId: 9,
        candidateId: 11,
        checkerId: 2,
        professionalTitle: "Producer",
        hometownAddress: "Yen Bai",
        expectedSalary: "2,431,844",
        currency: "₩",
        preferredWork: "Construction Worker",
        academicBackground: "Doctoral",
        expectedArea: "Cheonan",
        familySituation: "Medium",
        marriedStatus: "Married",
        numberOfFamily: "4",
        passportImg:
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReuEECQzwR2I_bFMxpB-03M4Bgoz5ivATToqiorqdvow&s",
        healthCheckImg:
            "https://novalaw.vn/wp-content/uploads/2022/10/Sample-of-a-work-permit-health-check-certificate-issued-in-Vietnam.png",
        policeCheckImg:
            "https://www.vietnamimmigration.com/wp-content/uploads/2021/07/criminal-record-certificate-no.2.jpg",
        koreanExamImg: "https://media.cakeresume.com/image/upload/v1628180772/murftgok0yzzhhkwn3r0.png",
        idCardFrontImg: "https://lawnet.vn/uploads/image/2023/06/03/014312635.jpg",
        idCardBackImg: "https://cdnimgen.vietnamplus.vn/t620/uploaded/wbxx/2021_02_24/chip_based_id_card_back.jpg",
        status: "Waiting",
        note: "",
        dateApplying: "March 23, 2023"
    },
    {
        applicationId: 10,
        candidateId: 12,
        checkerId: 3,
        professionalTitle: "Botanist",
        hometownAddress: "Moc Bai",
        expectedSalary: "2,137,008",
        currency: "₩",
        preferredWork: "Farmer",
        academicBackground: "Master",
        expectedArea: "Jeju City",
        familySituation: "Medium",
        marriedStatus: "Married",
        numberOfFamily: "5",
        passportImg:
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReuEECQzwR2I_bFMxpB-03M4Bgoz5ivATToqiorqdvow&s",
        healthCheckImg:
            "https://novalaw.vn/wp-content/uploads/2022/10/Sample-of-a-work-permit-health-check-certificate-issued-in-Vietnam.png",
        policeCheckImg:
            "https://www.vietnamimmigration.com/wp-content/uploads/2021/07/criminal-record-certificate-no.2.jpg",
        koreanExamImg: "https://media.cakeresume.com/image/upload/v1628180772/murftgok0yzzhhkwn3r0.png",
        idCardFrontImg: "https://lawnet.vn/uploads/image/2023/06/03/014312635.jpg",
        idCardBackImg: "https://cdnimgen.vietnamplus.vn/t620/uploaded/wbxx/2021_02_24/chip_based_id_card_back.jpg",
        status: "Waiting",
        note: "",
        dateApplying: "January 27, 2023"
    }
];
