export const Users = [
    {
        userId: 1,
        email: "admin@worknete9.com",
        password: "Password1",
        username: "admin1",
        name: "Admin",
        givenName: "",
        birthday: "",
        age: "30",
        phoneNumber: "443-5874-50",
        countryCode: "70000",
        phoneCode: "+84",
        gender: "Male",
        userLockedFlag: false,
        avatarImg: "https://i.pravatar.cc/300",
        role: "Owner",
        location: "Jacksonville",
        company: "HexaTech",
        establish_year: "1994"
    },
    {
        userId: 2,
        email: "a.stewart@randatmail.com",
        password: "123456",
        username: "a.stewart",
        age: "26",
        name: "Alford",
        givenName: "Stewart",
        birthday: "",
        phoneNumber: "394-6666-11",
        countryCode: "70000",
        phoneCode: "+84",
        gender: "Male",
        userLockedFlag: false,
        avatarImg: "https://i.pravatar.cc/300",
        role: "Admin",
        location: "Long Beach",
        company: "BuzzShift",
        establish_year: "2020"
    },
    {
        userId: 3,
        email: "g.evans@randatmail.com",
        password: "123456",
        username: "g.evans",
        age: "27",
        name: "Gianna",
        givenName: "Evans",
        birthday: "",
        phoneNumber: "928-3245-95",
        countryCode: "70000",
        phoneCode: "+84",
        gender: "Female",
        userLockedFlag: false,
        avatarImg: "https://i.pravatar.cc/300",
        role: "Admin",
        location: "San Francisco",
        company: "IT Business Solutions",
        establish_year: "2001"
    },
    {
        userId: 4,
        email: "l.crawford@randatmail.com",
        password: "123456",
        username: "l.crawford",
        age: "18",
        name: "Lucas",
        givenName: "Crawford",
        birthday: "",
        phoneNumber: "426-1847-87",
        countryCode: "70000",
        phoneCode: "+84",
        gender: "Male",
        userLockedFlag: false,
        avatarImg: "https://i.pravatar.cc/300",
        role: "Member",
        location: "Nashville",
        company: "HexaTech",
        establish_year: "1991"
    },
    {
        userId: 5,
        email: "r.richards@randatmail.com",
        password: "123456",
        username: "r.richards",
        name: "Richard",
        givenName: "Richards",
        birthday: "19",
        phoneNumber: "748-6668-73",
        countryCode: "70000",
        phoneCode: "+84",
        gender: "Male",
        userLockedFlag: false,
        avatarImg: "https://i.pravatar.cc/300",
        role: "Member",
        location: "Tampa",
        company: "Global Services Company",
        establish_year: "2003"
    },
    {
        userId: 6,
        email: "l.brown@randatmail.com",
        password: "123456",
        username: "l.brown",
        age: "30",
        name: "Lilianna",
        givenName: "Brown",
        birthday: "",
        phoneNumber: "806-3366-66",
        countryCode: "70000",
        phoneCode: "+84",
        gender: "Female",
        userLockedFlag: false,
        avatarImg: "https://i.pravatar.cc/300",
        role: "Member",
        location: "Seattle",
        company: "NeuWave",
        establish_year: "2006"
    },
    {
        userId: 7,
        email: "i.murray@randatmail.com",
        password: "123456",
        username: "i.murray",
        age: "27",
        name: "Isabella",
        givenName: "Murray",
        birthday: "",
        phoneNumber: "173-7696-36",
        countryCode: "70000",
        phoneCode: "+84",
        gender: "Female",
        userLockedFlag: false,
        avatarImg: "https://i.pravatar.cc/300",
        role: "Member",
        location: "Huangpu",
        company: "SkyVue",
        establish_year: "2017"
    },
    {
        userId: 8,
        email: "j.allen@randatmail.com",
        password: "123456",
        username: "j.allen",
        age: "21",
        name: "John",
        givenName: "Allen",
        birthday: "",
        phoneNumber: "291-2663-08",
        countryCode: "70000",
        phoneCode: "+84",
        gender: "Male",
        userLockedFlag: false,
        avatarImg: "https://i.pravatar.cc/300",
        role: "Member",
        location: "London",
        company: "Proactive Technologies",
        establish_year: "1992"
    },
    {
        userId: 9,
        email: "m.harris@randatmail.com",
        password: "123456",
        username: "m.harris",
        age: "25",
        name: "Mary",
        givenName: "Harris",
        birthday: "",
        phoneNumber: "323-7987-24",
        countryCode: "70000",
        phoneCode: "+84",
        gender: "Female",
        userLockedFlag: false,
        avatarImg: "https://i.pravatar.cc/300",
        role: "Member",
        location: "Hanoi",
        company: "Brainiac Solutions",
        establish_year: "2010"
    },
    {
        userId: 10,
        email: "r.turner@randatmail.com",
        password: "123456",
        username: "r.turner",
        age: "18",
        name: "Rubie",
        givenName: "Turner",
        birthday: "",
        phoneNumber: "525-8110-68",
        countryCode: "70000",
        phoneCode: "+84",
        gender: "Female",
        userLockedFlag: false,
        avatarImg: "https://i.pravatar.cc/300",
        role: "Member",
        location: "San Antonio",
        company: "PluRush",
        establish_year: "1995"
    },
    {
        userId: 11,
        email: "d.howard@randatmail.com",
        password: "123456",
        username: "d.howard",
        age: "30",
        name: "Derek",
        givenName: "Howard",
        birthday: "",
        phoneNumber: "853-3751-35",
        countryCode: "70000",
        phoneCode: "+84",
        gender: "Male",
        userLockedFlag: false,
        avatarImg: "https://i.pravatar.cc/300",
        role: "Member",
        location: "South Delhi",
        company: "InfoCube Technologies",
        establish_year: "2016"
    },
    {
        userId: 12,
        email: "m.carroll@randatmail.com",
        password: "123456",
        username: "m.carroll",
        age: "28",
        name: "Mike",
        givenName: "Carroll",
        birthday: "",
        phoneNumber: "025-9664-99",
        countryCode: "70000",
        phoneCode: "+84",
        gender: "Male",
        userLockedFlag: false,
        avatarImg: "https://i.pravatar.cc/300",
        role: "Member",
        location: "Meguro-ku",
        company: "FlowVolt",
        establish_year: "2006"
    }
];
